export { default as PageAuth } from './page-auth/PageAuth';
export { default as PageMain } from './page-main/PageMain';
export { default as PageError } from './page-error/PageError';
export { default as PageFaculties } from './page-faculties/PageFaculties';
export { default as PageFaculty } from './page-faculty/PageFaculty';
export { default as PageGroup } from './page-group/PageGroup';
export { default as PageSchedule } from './page-schedule/PageSchedule';
export { default as PageSubjects } from './page-subjects/PageSubjects';
export { default as PageProfile } from './page-profile/PageProfile';
